[pyprland]
plugins = [
 "scratchpads",
 "fetch_client_menu",
 "shift_monitors",
]

[scratchpads.term]
animation = "fromTop"
command = "foot --app-id=foot-dropterm"
class = "foot-dropterm"
position = "17% 5%"
size = "65% 40%"

[scratchpads.yazi]
animation = "fromTop"
command = "foot --app-id=foot-yazi -e yazi"
class = "foot-yazi"
position = "17% 5%"
size = "65% 40%"

[scratchpads.bluetooth]
animation = "fromTop"
command = "foot --app-id foot-bluetooth -e bluetui"
class = "foot-bluetooth"
position = "59% 5%"
size = "40% 50%"