[pyprland]
plugins = [
 "scratchpads",
 "fetch_client_menu",
 "shift_monitors",
]

[fetch_client_menu]
engine = "wofi"

[scratchpads.term]
animation = "fromTop"
command = "foot --app-id=foot-dropterm"
class = "foot-dropterm"
position = "17% 5%"
size = "65% 40%"

[scratchpads.yazi]
animation = "fromTop"
command = "foot --app-id=foot-yazi -e yazi"
class = "foot-yazi"
position = "17% 5%"
size = "65% 40%"