[pyprland]
plugins = [
 "scratchpads",
 "fetch_client_menu",
 "shift_monitors",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
position = "17% 5%"
size = "65% 40%"

[scratchpads.bluetooth]
animation = "fromTop"
command = "kitty --class kitty-bluetooth -e bluetui"
class = "kitty-bluetooth"
position = "59% 5%"
size = "40% 50%"